const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const Users = new Schema({
    userName:{
        type:String
    },
    password:{
        type:String
    },
    mail:{
        type:String
    },
    referalCount:{
        type:Number,
        default:1
    },
    ticket:{
        type:Number,
        default:4
    },
    diamond:{
        type:Number,
        default:100
    },
    luckWheel:{
        type:Number,
        default:1
    },
    weeklyScore:{
        type:Number,
        default:0
    },
    monthlyScore:{
        type:Number,
        default:0
    },
    allScore:{
        type:Number,
        default:0
    },
    userAvatar:{
        type:String,
        default:'/uploads/default/user.png',
    },
    avatars:[],
    userFrame:{
        type:String,
        default:'/uploads/default/user.png',
    },
    dailyQuestions:{
            type:Number,
            default:1
    },
    frames:[],
    oneSignal:{ 
        type:String,
        default:'a'
    },
    userBanType:{
        type:Number,
        default:0,
    },
    userMailCode:{
        type:String,
    },
    questionId:[],
    userCreated:{
        type:Date,
        default:Date.now()
    }
});

module.exports = mongoose.model('Users', Users);
